---
title: "package NEWS - please read"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Major changes

* new functions for visualizing anomalies in maps (autoplot_anomaly_map) and time series (autoplot_anomaly_ts) 
* new aggregation type "xdays" allows the aggregation over daily intervals of length x (e.g. weekly aggregation if x=7). No autoplot functions implemented yet for this aggregation type
* changes of method of quantile calculation. We recommend to recalculate your results from previous calculations with the updated version.
* changes in make_object: Function now additionally returns "jdays" for calculation of quantiles. Consider recalculating your objects in case you are using old objects.

## bug fixes
* calc_index: cdd calculation was changed from cdd<=1 to cdd <1
* ..._map functions: if  all values to be plotted are NA, no plot is return
* autoplot_climatology map: now also allows the visualization of percentiles
* autoplot_verification map: now differs between NA values or values where the climatology shows no variation (now colored in grey) and values with no or little skill (in white)
* autoplot_fc_map: NA values and values where the climatology shows no variability now have the color NAcol if they have no skill, before they had the noskill color. Ff plot_climatology=TRUE, the tercile boundaries of the observations will be plotted in seperate maps.
* autoplot_trend_map: arguments p_breaks/p_nlev can now be passed 
* autoplot_ts_stations: new argument plot_legend to choose, whether legend should be plotted or not.



